import React, { useState, useEffect } from "react"
import dynamic from "next/dynamic";

import { Navbar, Hero, Contact, Projects, Skills, About, Footer, PDFViewer } from '../components'



export default function Home() {

  const normal = `text-gray-600 bg-[#ecf0f3]`
  const black = `bg-gray-900 text-gray-300`

  const [showResume, setShowResume] = useState(false)
  const [dark, setDark] = useState(true)
  
useEffect(() => {
  if (sessionStorage.theme === 'dark' || (!('theme' in sessionStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
    document.documentElement.classList.add('dark')
    console.log('dark mode on')
  } else {
    document.documentElement.classList.remove('dark')
  }
  
}, [dark])

  const body = () =>{
    if(showResume){
      return  <PDFViewer setShowResume={setShowResume} />
    }
    return (
      <div className={`${dark ? black : normal}`}>
          <Navbar setShowResume={setShowResume} theme={dark} setDark={setDark}/>
          <Hero theme={dark} />
          <About theme={dark} />
          <Skills theme={dark} />
          <Projects theme={dark} />
          <Contact theme={dark} />
        </div>
    )
  }

  return (
    <div className="w-full h-full">
      <header>
        <title>Yair | Full-Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </header>
      {body()}

    </div>
  )
}
