import React, { useState, useEffect } from "react"
import dynamic from "next/dynamic";

import { Navbar, Hero, Contact, Projects, Skills, About, Footer, PDFViewer } from '../components'



export default function Home() {


  const [showResume, setShowResume] = useState(false)
  const [dark, setDark] = useState(false)

  useEffect(() => {
    let theme = sessionStorage.getItem('theme')
    if (theme !== 'undefined' && theme === 'light') {
      document.documentElement.classList.remove('dark')
      setDark(false)
    }

  }, [])


  useEffect(() => {
    if (dark) {
      sessionStorage.setItem(`theme`, 'dark')
    }
    else {
      sessionStorage.setItem(`theme`, 'light')
    }

    if (sessionStorage.theme === 'dark' || (!('theme' in sessionStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
      document.documentElement.classList.add('dark')
      console.log('dark mode on')
    } else {
      document.documentElement.classList.remove('dark')
    }

  }, [dark])




  const body = () => {
    if (showResume) {
      return <PDFViewer setShowResume={setShowResume} />
    }
    return (
      <div >
        <Navbar setShowResume={setShowResume} theme={dark} setDark={setDark} />
        <Hero />
        <About />
        <Skills />
        <Projects />
        <Contact />
      </div>
    )
  }

  return (
    <div className="w-full h-full text-gray-600 bg-[#ecf0f3] dark:bg-gray-900 dark:text-gray-300">
      <header>
        <title>Yair Full-Stack </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href="/../public/assets/YNFS.png" />
      </header>
      {body()}

    </div>
  )
}
